FROM ubuntu:22.04

# maintainer: volkmann@devpool.net

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update 

RUN apt install -y wget gawk git-core diffstat unzip texinfo \
    gcc-multilib build-essential chrpath socat cpio python3 \ 
    python3-pip python3-pexpect xz-utils debianutils iputils-ping \
    libsdl1.2-dev xterm tar locales net-tools rsync sudo vim curl zstd \
    liblz4-tool libssl-dev bc lzop libgnutls28-dev efitools git-lfs file \
    iproute2 apt-utils 

RUN apt install -y sudo

# Set up locales
RUN locale-gen en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

# Yocto needs 'source' command for setting up the build environment, so replace
# the 'sh' alias to 'bash' instead of 'dash'.
RUN rm /bin/sh && ln -s bash /bin/sh

COPY run.sh /usr/bin/

RUN  chmod 755 /usr/bin/run.sh

ENTRYPOINT ["/usr/bin/run.sh"]
